export class RegexUtils {
	static fiscalReportPattern = /^(?<raw> *?DOCUMENTO (?<type>GESTIONALE) *?\n(.*\n)*?(VENDITE *?(?<sells>(\.?[\d]{1,3})*?,[\d]{2})\n){1}(GRAN TOTALE *?(?<grandTotal>(\.?[\d]{1,3})*?,[\d]{2})){1}(?<vats>(.*\n)*?)(?<payments>(PAGATO.*?\n)*?)(FATTURE *?(?<invoices>[\d]+)\n){1}(TOT\. FATTURE *?(?<invoicesTotal>(\.?[\d]{1,3})*?,[\d]{2})\n){1}(.*\n)*?(CHIUSURA GIORNALIERA N\. *?(?<closureN>[\d]{4})\n){1}(DOCUMENTI COMMERCIALI *?(?<fiscalDocuments>[\d]{4})\n){1}(DOCUMENTI GESTIONALI *?(?<managementDocuments>[\d]{4})\n){1}(LETTURE M\.P\.RIEPILOGO *?(?<summaryReadings>[\d]{4})\n){1}(.*\n)*?( +?(?<datetime>[\d]{2}-[\d]{2}-[\d]{4} [\d]{2}:[\d]{2}) +?\n){1}( +?(DOCUMENTO N\.|DOC\.GESTIONALE N\.) (?<closure>[\d]{4})-(?<number>[\d]{4}) +?\n){1}(RIPRISTINI *?(?<restores>[\d]{4})\n){1}(DGFE:(?<dgfeNumber>[\d]{2}) SIGILLO FISCALE:(?<fiscalSeal>[0-9A-F]+) *?\n)( *?(?<serialNumber>[7][2][a-zA-Z]{2}[\d]{7}).*?){1})$/gm;

	static fiscalReportVatDetailsPattern = /^IVA [\d]{1,2} ([\d]{1,2},[\d]{2}%|.{2}) : +?\n TOTALE VENDITE *?(?<sellsGrandTotal>(\.?[\d]{1,3})*?,[\d]{2})\n IMPONIBILE VENDITE *?(?<sellsNetTotal>(\.?[\d]{1,3})*?,[\d]{2})\n IVA VENDITE *?(?<sellsVatTotal>(\.?[\d]{1,3})*?,[\d]{2})\n.*?\nTOTALE IVA (?<id>[\d]{1,2}) (?<vat>[\d]{1,2},[\d]{2}%|.{2}) *?(?<total>(\.?[\d]{1,3})*?,[\d]{2})\n/gm;

	static fiscalReportPaymentDetailsPattern = /^(?<description>([\w]+? *?){2,}) *? (?<value>(\.?[\d]{1,3})*?,[\d]{2})\n/gm;

	static fiscalDocumentPattern = /^(?<raw> *?DOCUMENTO (?<type>COMMERCIALE) *?\n(.*\n)*?(?<items>DESCRIZIONE.*?\n(.*\n)*?)((TOTALE COMPLESSIVO *?(?<grandTotal>(\.?[\d]{1,3})*?,[\d]{2})\n)(di cui IVA *?(?<vatTotal>(\.?[\d]{1,3})*?,[\d]{2})\n)?(.*\n)*?(?<payments>\-+?\n(?<paymentsType>(.*?\n)*?)\-+?\n)(.*\n)*?(Importo pagato[ ]+?(?<paymentTotal>(\.?[\d]{1,3})*?,[\d]{2})\n).*?( +?(?<datetime>[\d]{2}-[\d]{2}-[\d]{4} [\d]{2}:[\d]{2}) +?\n){1})(( +?DOCUMENTO N\. (?<closure>[\d]{4})-(?<number>[\d]{4}) +?\n){1}.*?(.*?(?<serialNumber>[7][2][a-zA-Z]{2}[\d]{7}).*?){1}))$/gm;

	static fiscalDocumentItemsPattern = /^((?<description>[\w]+?) *?((?<vat>[\d]{1,2})%) *?(?<value>(\.?[\d]{1,3})*?,[\d]{2})\n)( *?n\.(?<qty>[\d]{1,5}) \* (?<unitValue>(\.?[\d]{1,3})*?,[\d]{2}) *?\n)?((?<discountDescription>[\w]+?)( (?<discountPerc>[\d]{1,3})%)? *?((?<discountVat>[\d]{1,2})%) *?(?<discountValue>\-(\.?[\d]{1,3})*?,[\d]{2}))?/gm;

	static fiscalDocumentPaymentsPattern = /^(?<description>[\w \-\+\*\.]+?) *?(?<value>(\.?[\d]{1,3})*?,[\d]{2})$/gm;
}